version: "3"

services:
  mongo:
    image: mongo:latest
    restart: on-failure
    network_mode: "host"
    # volumes:
    #   - ./src/resources/initMongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    command: mongod
    # ports:
    #   - 27017:27017
  test-repo:
    build: .
    restart: on-failure
    network_mode: "host"
    environment:
      WAIT_HOSTS: mongo:27017
    # ports:
    #   - 80:80
    depends_on:
      - mongo
